apiVersion: v1
kind: Secret
metadata:
  name: assetpro-apis-secret
  namespace: stage
  labels:
    tier: backend
    app: assetpro-apis
data:
  DB_DIALECT: bXNzcWw=
  DB_HOST: MzUuMTcwLjUxLjcx
  DB_PORT: NTQzMg==
  DB_USER: QVBSZXBvcnRz
  DB_PASSWORD: ISMlJihQcm8yMw==
  DB_NAME: QXNzZXRQcm9LZW5jbw==
  JWT_SECRET: cHJpdmF0ZQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assetpro-apis-configmap
  namespace: stage
  labels:
    tier: backend
    app: assetpro-apis
data:

---
apiVersion: v1
kind: Service
metadata:
  name: assetpro-apis-svc
  namespace: stage
  labels:
    svc: assetpro-apis
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      name: tcp
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: assetpro-apis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetpro-apis-deployment
  namespace: stage
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: assetpro-apis
  template:
    metadata:
      annotations:
      labels:
        app: assetpro-apis
    spec:
      containers:
        - name: assetpro-apis-image
          image: 562740050455.dkr.ecr.eu-west-1.amazonaws.com/assetpro-apis-service:stage
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: assetpro-apis-configmap
            - secretRef:
                name: assetpro-apis-secret
          ports:
            - containerPort: 4000
            - containerPort: 3000
